ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/config/routes.rb
Rails.application.routes.draw do
  resources :cuicuis
  resources :users
  resources :likes
  resources :likes
  resources :comments

end

ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/app/models/user.rb
class User < ActiveRecord::Base
  has_many :cuicuis
  has_many :likes
  has_many :comments
end

ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :since, :admin, :country)
  end
end

ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :since %><br>
    <%= f.number_field :since %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/app/views/users/edit.html.erb
<!-- comment -->
<%if false%>
<% title "Editing User"%>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>





<%end%>

ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/app/views/users/index.html.erb
<!-- comment -->
<%if false%>
<p id="notice"><%= notice %></p>

<% title "Listing Users"%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Since</th>
      <th>Admin</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.since %></td>
        <td><%= user.admin %></td>
        <td><%= user.country %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>


<%end%>

ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/app/views/users/new.html.erb
<!-- comment -->
<%if false%>
<% title "New User"%>

<%= render 'form' %>

<%= link_to 'Back', users_path %>





<%end%>

ToDo/rubyonrails/6 - Ruby on Rails Piscine/3/j05/ex03/tweetos_aka_hello_rails/app/views/users/show.html.erb
<!-- comment -->
<%if false%>
<h1 id="notice"><%= notice %></p>
<h1><%="#{@user.name} details"%> <%= link_to 'Edit', edit_user_path(@user) ,class: "btn pri Blacklist" %> <%= link_to 'Back', users_path ,class: "btn pri Blacklist" %></h1>
</br>
<div class="">
  <h1 class="tag">
    <strong>Name:</strong>
    <%= @user.name %>
</h1>

  <h1 class="tag">
    <strong>Email:</strong>
    <%= @user.email %>
</h1>

  <h1 class="tag">
    <strong>Since:</strong>
    <%= @user.since %>
</h1>

  <h1 class="tag">
    <strong>Country:</strong>
    <%= @user.country %>
</h1>
  <h1 class="tag">
    <strong>Likes:</strong>
    <%= @user.fame %>
</h1>
  <h1 class="tag">
    <strong>Country:</strong>
    <%= @user.country %>
</h1>
</div>
</br>

<%if false %> <!-- a decomenter dans l' ex07 -->
    <table class="split_table">
      <thead>
        <tr>
          <th>Likes</th>
          <th>Content</th>
          <th>Date</th>
        </tr>
      </thead>

      <tbody>
        <% @user.top_cuicui.each do |cui| %>
          <tr>
            <td><%= cui.likes.count %></td>
            <td><%= link_to "#{cui.content }" , cuicui_path(cui.id) %></td>
            <td><%= cui.created_at  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>



<table class="split_table_right">
  <thead>
    <tr>
      <th>Comment n°</th>
      <th>Cuicui n°</th>
      <th>Content</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @user.responses.each do |res| %>
      <tr>
        <td><%= res.id %></td>
        <td><%= link_to "#{res.cuicui_id}" ,cuicui_path(res.cuicui_id) %></td>
        <td><%= res.content  %></td>
        <td><%= res.created_at  %></td>
      </tr>
    <% end %>
  </tbody>
</table>


    <table>
      <thead>
        <tr>
          <th>Likes</th>
          <th>Content</th>
          <th>Date</th>
        </tr>
      </thead>

      <tbody>
        <% @user.cuicuis.each do |cui| %>
          <tr style="border:4px">
            <td><%= cui.likes.count %></td>
            <td><h3>Cuiui: <%= cui.content  %></h3></td>
            <td><%= cui.created_at  %></td>
          </tr>
          <% cui.comments.each  do |com| %>
          <tr class="resp">
            <td>
              <%= link_to "#{User.find(com.user_id).name}" , user_path(com.user_id)%>
            </td>
            <td colspan="2">
              <%= com.content%>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>


  <%end%> <!-- a decomenter dans l' ex07 -->
<%end%>